package tech.onetap.util.killsay;

/** Готовые пресеты фраз KillSay. */
public final class KillSayPresets {

    public static final String[] KILL_MESSAGES = {
            "!{player} Выебан чмошник / LayF Infinyty",
            "!{player} был удалён из этого мира / LayF Infinyty",
            "!{player} спавн тебя ждет хуесос / LayF Infinyty",
            "!{player} -ezz Нищий / LayF Infinyty",
            "!{player} прощай мир... Прощай / LayF Infinyty",
            "!{player} кончился Твой прайм / LayF Infinyty",
            "!{player} не смог выжить и подох / LayF Infinyty",
            "!{player} проиграл битву моему Члену / LayF Infinyty",
            "!{player} отсылает в лобби / LayF Infinyty",
            "!{player} Выебан уничтожен / LayF Infinyty",
            "!{player} не достоин жизни / LayF Infinyty",
            "!{player} лег в засыпание / LayF Infinyty",
            "!{player} удален с сервера / LayF Infinyty",
            "!{player} Ты был слаб / LayF Infinyty",
            "!{player} не выдержал борьбы с моим членом / LayF Infinyty",
            "!{player} сдался без боя / LayF Infinyty",
            "!{player} попал под раздачу спермы / LayF Infinyty",
            "!{player} не смог противостоять / LayF Infinyty",
            "!{player} кончился быстро / LayF Infinyty",
            "!{player} был бесполезен / LayF Infinyty",
            "!{player} лег в небытие в канаве / LayF Infinyty",
            "!{player} исчез навсегда при аборте / LayF Infinyty",
            "!{player} не прошел проверку и был выебан / LayF Infinyty",
            "!{player} был Выебан / LayF Infinyty",
            "!{player} не осилил / LayF Infinyty",
            "!{player} пал жертвой / LayF Infinyty",
            "!{player} не справился / LayF Infinyty",
            "!{player} был слишком слаб / LayF Infinyty",
            "!{player} не устоял / LayF Infinyty",
            "!{player} получил хуём по лбу / LayF Infinyty",
            "!{player} был устранен / LayF Infinyty",
            "!{player} не прошел / LayF Infinyty",
            "!{player} закончился / LayF Infinyty",
            "!{player} не смог защититься / LayF Infinyty",
            "!{player} был сокрушен / LayF Infinyty",
            "!{player} не выдержал давления / LayF Infinyty",
            "!{player} лег на дно / LayF Infinyty",
            "!{player} был удален / LayF Infinyty",
            "!{player} не смог сбежать / LayF Infinyty",
            "!{player} попал под удар / LayF Infinyty",
            "!{player} не успел среагировать / LayF Infinyty",
            "!{player} был надомнен / LayF Infinyty",
            "!{player} не устоял перед силой / LayF Infinyty",
            "!{player} сгорел дотла / LayF Infinyty",
            "!{player} был раздавлен / LayF Infinyty",
            "!{player} не прошел тест / LayF Infinyty",
            "!{player} лег в вечный сон / LayF Infinyty",
            "!{player} был стерт / LayF Infinyty",
            "!{player} не смог противостоять силе / LayF Infinyty",
            "!{player} сдох в бою / LayF Infinyty",
            "!{player} был уничтожен / LayF Infinyty",
            "!{player} не выжил в этой игре / LayF Infinyty",
            "!{player} лег в могилу / LayF Infinyty",
            "!{player} был ликвидирован / LayF Infinyty",
            "!{player} не справился с вызовом / LayF Infinyty",
            "!{player} был осужден на смерть / LayF Infinyty",
            "!{player} не смог уйти от удара / LayF Infinyty",
            "!{player} Блять попал под горячую руку / LayF Infinyty",
            "!{player} был сломлен / LayF Infinyty",
            "!{player} не устоял перед мощью / LayF Infinyty",
            "!{player} кончился очень быстро / LayF Infinyty",
            "!{player} не прошел через меня / LayF Infinyty",
            "!{player} был отправлен в лобби / LayF Infinyty",
            "!{player} не смог выжить в этом мире / LayF Infinyty",
            "!{player} лег под ноги / LayF Infinyty",
            "!{player} был устранен без следа / LayF Infinyty",
            "!{player} не выдержал битву / LayF Infinyty",
            "!{player} был разбит / LayF Infinyty",
            "!{player} не смог защитить себя / LayF Infinyty",
            "!{player} лег в вечность / LayF Infinyty",
            "!{player} был стерт с лица земли / LayF Infinyty",
            "!{player} не справился с задачей / LayF Infinyty",
            "!{player} был отправлен в бездну / LayF Infinyty",
            "!{player} не устоял перед лицом смерти / LayF Infinyty",
            "!{player} попал под раздачу LayF Infinyty",
            "!{player} был уничтожен без жалости / LayF Infinyty",
            "!{player} не смог вырваться / LayF Infinyty",
            "!{player} лег навсегда / LayF Infinyty",
            "!{player} был выебан силой / LayF Infinyty",
            "!{player} не прошел испытание / LayF Infinyty",
            "!{player} был раздавлен властью / LayF Infinyty",
            "!{player} не выжил в схватке / LayF Infinyty",
            "!{player} лег в небытие / LayF Infinyty",
            "!{player} был устранен системой / LayF Infinyty",
            "!{player} не смог противостоять воле / LayF Infinyty",
            "!{player} пал жертвой силы / LayF Infinyty",
            "!{player} был осужден на небытие / LayF Infinyty",
            "!{player} не устоял перед доминированием / LayF Infinyty",
            "!{player} кончился как всегда / LayF Infinyty",
            "!{player} в конце всегда LayF Infinyty",
            "!{player} не смог избежать судьбы / LayF Infinyty",
            "!{player} был удален из игры / LayF Infinyty",
            "!{player} не выдержал испытание / LayF Infinyty",
            "!{player} лег под ударом / LayF Infinyty",
            "!{player} был стерт в пыль / LayF Infinyty",
            "!{player} не справился с реальностью / LayF Infinyty",
            "!{player} кончился в конце / LayF Infinyty",
            "!{player} в конце всегда побеждает LayF Infinyty",
            "!{player} не смог уйти от конца / LayF Infinyty",
            "!{player} был уничтожен LayF Infinyty",
            "!{player} не выжил в конце / LayF Infinyty",
            "!{player} лег в конец / LayF Infinyty",
            "!{player} в конце всегда LayF Infinyty"
    };

    public static final String[] TOTEM_MESSAGES = {
            "!{player} прототемил и остался жив / LayF Infinyty",
            "!{player} сожрал свой тотем / LayF Infinyty",
            "!{player} тотем на исходе / LayF Infinyty",
            "!{player} вынул тотем из задницы / LayF Infinyty",
            "!{player} -тотем опять / LayF Infinyty",
            "!{player} тотем не спасёт тебя / LayF Infinyty",
            "!{player} снова прототемил / LayF Infinyty",
            "!{player} тотемчик кончился / LayF Infinyty",
            "!{player} папа тотем на месте / LayF Infinyty",
            "!{player} тотем прожёг / LayF Infinyty",
            "!{player} нажрался тотемов / LayF Infinyty",
            "!{player} тотем в жопе / LayF Infinyty",
            "!{player} тотем уже не поможет / LayF Infinyty",
            "!{player} тотем улетел / LayF Infinyty",
            "!{player} тотем закончился досрочно / LayF Infinyty",
            "!{player} тотем потрачен впустую / LayF Infinyty",
            "!{player} тотем сгорел / LayF Infinyty",
            "!{player} тотем использован / LayF Infinyty",
            "!{player} тотем в деле / LayF Infinyty",
            "!{player} тотем протащен / LayF Infinyty",
            "!{player} -тотем и снова / LayF Infinyty",
            "!{player} тотем проглотил / LayF Infinyty",
            "!{player} тотем съеден / LayF Infinyty",
            "!{player} тотем в расход / LayF Infinyty",
            "!{player} тотем не вечен / LayF Infinyty",
            "!{player} тотем лопнул / LayF Infinyty",
            "!{player} тотем треснул / LayF Infinyty",
            "!{player} тотем хрустнул / LayF Infinyty",
            "!{player} тотем закончился как прайм / LayF Infinyty",
            "!{player} тотем опять в ход / LayF Infinyty",
            "!{player} тотем на счётчике убавился / LayF Infinyty",
            "!{player} тотем в мусорку / LayF Infinyty",
            "!{player} тотем бесславно пал / LayF Infinyty",
            "!{player} тотем спас жопу / LayF Infinyty",
            "!{player} тотем отбил удар / LayF Infinyty",
            "!{player} тотем отработал / LayF Infinyty",
            "!{player} тотем в деле снова / LayF Infinyty",
            "!{player} тотем проглочен как конфета / LayF Infinyty",
            "!{player} тотем на перекус / LayF Infinyty",
            "!{player} тотем закуской / LayF Infinyty",
            "!{player} тотем это не спасение / LayF Infinyty",
            "!{player} тотем лишь отсрочка / LayF Infinyty",
            "!{player} тотем не спасёт второй раз / LayF Infinyty",
            "!{player} тотем на исходе считай / LayF Infinyty",
            "!{player} тотем третий по счёту / LayF Infinyty",
            "!{player} тотем кончается / LayF Infinyty",
            "!{player} тотем снова в расход / LayF Infinyty",
            "!{player} тотем в огонь / LayF Infinyty",
            "!{player} тотем прогорел / LayF Infinyty",
            "!{player} тотем скушан / LayF Infinyty",
            "!{player} тотем не вечная броня / LayF Infinyty",
            "!{player} тотем как вода / LayF Infinyty",
            "!{player} тотем в бездну / LayF Infinyty",
            "!{player} тотем улетел в небо / LayF Infinyty",
            "!{player} тотем полетел / LayF Infinyty",
            "!{player} тотем обнулился / LayF Infinyty",
            "!{player} тотем на нуле / LayF Infinyty",
            "!{player} тотем израсходован / LayF Infinyty",
            "!{player} тотем пустой / LayF Infinyty",
            "!{player} тотем в топку / LayF Infinyty",
            "!{player} тотем погас / LayF Infinyty",
            "!{player} тотем не сработал как надо / LayF Infinyty",
            "!{player} тотем чуть не спас / LayF Infinyty",
            "!{player} тотем отсрочил смерть / LayF Infinyty",
            "!{player} тотем дал минуту жизни / LayF Infinyty",
            "!{player} тотем продлил мучения / LayF Infinyty",
            "!{player} тотем отложил казнь / LayF Infinyty",
            "!{player} тотем и снова ты жив / LayF Infinyty",
            "!{player} тотем бесполезен против меня / LayF Infinyty",
            "!{player} тотем не поможет от лага / LayF Infinyty",
            "!{player} тотем сгорел в бою / LayF Infinyty",
            "!{player} тотем против кристалов не спасает / LayF Infinyty",
            "!{player} тотем проиграл моему урону / LayF Infinyty",
            "!{player} тотем вылетел / LayF Infinyty",
            "!{player} тотем крякнул / LayF Infinyty",
            "!{player} тотем щёлкнул / LayF Infinyty",
            "!{player} тотем треснул пополам / LayF Infinyty",
            "!{player} тотем догорел / LayF Infinyty",
            "!{player} тотем в мусор / LayF Infinyty",
            "!{player} тотем потрачен зря / LayF Infinyty",
            "!{player} тотем ушёл в никуда / LayF Infinyty",
            "!{player} тотем испарился / LayF Infinyty",
            "!{player} тотем растворился / LayF Infinyty",
            "!{player} тотем исчез / LayF Infinyty",
            "!{player} тотем сдулся / LayF Infinyty",
            "!{player} тотем на ветер / LayF Infinyty",
            "!{player} тотем в пустоту / LayF Infinyty",
            "!{player} тотем на сдачу / LayF Infinyty",
            "!{player} тотем дешевле мусора / LayF Infinyty",
            "!{player} тотем не спас от омеги / LayF Infinyty",
            "!{player} тотем против LayF бессилен / LayF Infinyty",
            "!{player} тотем и так / LayF Infinyty",
            "!{player} тотем без шансов / LayF Infinyty",
            "!{player} тотем это конец / LayF Infinyty",
            "!{player} тотем последний был / LayF Infinyty",
            "!{player} тотем ушёл в мир иной / LayF Infinyty",
            "!{player} тотем упокоился / LayF Infinyty",
            "!{player} тотем похоронен / LayF Infinyty",
            "!{player} тотем RIP / LayF Infinyty",
            "!{player} тотем отмучился / LayF Infinyty",
            "!{player} тотем сдох как ты скоро / LayF Infinyty"
    };

    private KillSayPresets() {
    }
}